{{- if and .Values.storage.enabled (not .Values.storage.existingClaim) (eq (include "vaultwarden.workloadType" .) "Deployment") -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
{{- end }}
