{{- $databaseType := lower .Values.database.type -}}
{{- if and (ne $databaseType "sqlite") (not .Values.database.external.existingSecret) (or .Values.database.external.connectionString.value .Values.database.external.username.value .Values.database.external.password.value) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.database.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.database.external.connectionString.value }}
  {{ $.Values.database.external.connectionString.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.external.username.value }}
  {{ $.Values.database.external.username.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.database.external.password.value }}
  {{ $.Values.database.external.password.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
{{ end }}
{{- if and (not .Values.security.hibp.existingSecret) .Values.security.hibp.apiKey.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.hibp.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.security.hibp.apiKey.existingSecretKey }}: {{ .Values.security.hibp.apiKey.value | b64enc | quote }}
{{ end }}
{{- if and .Values.mfa.yubico.enabled (not .Values.mfa.yubico.existingSecret) .Values.mfa.yubico.secretKey.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.yubico.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mfa.yubico.secretKey.existingSecretKey }}: {{ .Values.mfa.yubico.secretKey.value | b64enc | quote }}
{{ end }}
{{- if and .Values.mfa.duo.enabled (not .Values.mfa.duo.existingSecret) .Values.mfa.duo.sKey.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.duo.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mfa.duo.sKey.existingSecretKey }}: {{ .Values.mfa.duo.sKey.value | b64enc | quote }}
{{ end }}
{{- if and .Values.smtp.enabled (not .Values.smtp.existingSecret) (or .Values.smtp.username.value .Values.smtp.password.value) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.smtp.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.smtp.username.value }}
  {{ $.Values.smtp.username.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.smtp.password.value }}
  {{ $.Values.smtp.password.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
{{ end }}
{{- if and (not .Values.config.disableAdminToken) .Values.adminToken }}
{{- if not .Values.adminToken.existingSecret }}
{{- $secretName := include "vaultwarden.adminToken.secretName" . -}}
{{- $secretKey := default "ADMIN_TOKEN" .Values.adminToken.existingSecretKey -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret (hasKey $existingSecret.data $secretKey) }}
  {{ $secretKey }}: {{ index $existingSecret.data $secretKey }}
  {{- else if .Values.adminToken.value }}
  {{ $secretKey }}: {{ .Values.adminToken.value | b64enc | quote }}
  {{- else }}
  {{ $secretKey }}: {{ randAlphaNum 48 | b64enc | quote }}
  {{- end }}
{{ end }}
{{ end }}
{{- if and .Values.pushNotifications.enabled (not .Values.pushNotifications.existingSecret) (or .Values.pushNotifications.installationId.value .Values.pushNotifications.installationKey.value) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.pushNotifications.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.pushNotifications.installationId.value }}
  {{ $.Values.pushNotifications.installationId.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.pushNotifications.installationKey.value }}
  {{ $.Values.pushNotifications.installationKey.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
{{ end }}
{{- if and .Values.sso.enabled (not .Values.sso.existingSecret) (or .Values.sso.clientId.value .Values.sso.clientSecret.value) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.sso.secretName" . }}
  labels:
    app.kubernetes.io/component: vaultwarden
{{ include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.sso.clientId.value }}
  {{ $.Values.sso.clientId.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.sso.clientSecret.value }}
  {{ $.Values.sso.clientSecret.existingSecretKey }}: {{ . | b64enc | quote }}
  {{- end }}
{{ end }}
