suite: test vaultwarden serviceaccount

templates:
  - templates/serviceaccount.yaml

release:
  name: vaultwarden
  namespace: vaultwarden

chart:
  version: 1.0.0
  appVersion: 1.0.0

tests:
  - it: should not create serviceaccount when serviceAccount.create is false
    set:
      serviceAccount:
        create: false
    asserts:
      - hasDocuments:
          count: 0

  - it: should set serviceaccount annotations when configured
    set:
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/vaultwarden
    asserts:
      - equal:
          path: metadata.annotations["eks.amazonaws.com/role-arn"]
          value: arn:aws:iam::111122223333:role/vaultwarden

  - it: should disable serviceaccount automount when configured
    set:
      serviceAccount:
        automount: false
    asserts:
      - equal:
          path: automountServiceAccountToken
          value: false
