suite: Test NOTES.txt
templates:
- NOTES.txt
tests:
- it: should not show deprecation notices when no deprecated fields are set
  set: {}
  asserts:
  - matchRegex:
      path: raw
      pattern: '1\. Get the application URL by running these commands:\n\s+echo "Visit http://127\.0\.0\.1:8080 to use your application"\n\s+kubectl --namespace NAMESPACE port-forward svc/RELEASE-NAME-n8n 8080:5678\n?'
  - notMatchRegex:
      path: raw
      pattern: '!!! We detected deprecated root level .* configuration usage'
- it: should not show deprecation notices for empty or undefined fields
  set:
    volumes: []
    main:
      resources: {}
  asserts:
  - notMatchRegex:
      path: raw
      pattern: '!!! We detected deprecated root level resources configuration usage'
  - notMatchRegex:
      path: raw
      pattern: '!!! We detected deprecated root level volumes configuration usage'
