apiVersion: v2
name: vaultwarden
description: Helm chart for Vaultwarden - an unofficial Bitwarden-compatible server written in Rust.
icon: https://raw.githubusercontent.com/dani-garcia/vaultwarden/refs/heads/main/resources/vaultwarden-icon.svg
type: application
version: 1.0.6
appVersion: "1.37.0"
kubeVersion: ">=1.24.0-0"
home: https://github.com/dani-garcia/vaultwarden
sources:
  - https://github.com/dani-garcia/vaultwarden
  - https://github.com/dalamudx/helm-charts
keywords:
  - vaultwarden
  - bitwarden
  - password-manager
